services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codecollab-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///codecollab.db
    volumes:
      - ./backend/codecollab.db:/app/codecollab.db
    networks:
      - codecollab-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    container_name: codecollab-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - codecollab-network
    restart: unless-stopped

networks:
  codecollab-network:
    driver: bridge

volumes:
  db_data: